name: linting, testing, building
on: 
    push:
        branches: [ master, process/v2 ]
    pull_request: 
        branches: [ master ]
jobs: 
    pipline: 
        runs-on: ubuntu-latest
        strategy: 
            matrix: 
                node-version: [ 18.x ]
        steps: 
            - uses: actions/checkout@v2
            - name: Starting Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with: 
                node-version: ${{ matrix.node-version }}
            - name: install modules
              run: npm install
            - name: build prodaction project
              run: npm run build:prod
            - name: linting project
              run: npm run lint
            - name: linting css project
              run: npm run style:lint
            - name: units
              run: npm run unit

